openapi: 3.0.3
info:
  title: Task Fire Api
  description: Task fire api
  version: 1.0.0
servers:
  - url: 'https//taskfireapi.jamesellerbee.com'

tags:
  - name: accounts
    description: Authentication and registration
  - name: tasks
    description: CRUD operations for Tasks associated with an account.

paths:
  /accounts:
    get:
      tags:
        - accounts
      summary: Returns a list of accounts
      description: Returns a list of accounts that your token can access with each account's password obfuscated
      parameters:
        - name: name
          schema:
            type: string
            example: Bob
          allowReserved: false
          in: path
          deprecated: false
          description: The name of the account to include in the response
          required: false
          explode: false
          allowEmptyValue: false
          style: matrix
      responses:
        200:
          description: List of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

  /auth:
    post:
      tags:
        - accounts
      summary: Provides the account ID and sets the JWT token in the response cookies.
      description: Provides a json object containing the account ID of the account used to authenticate and the JWT token to access protected routes.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        200:
          description: Json object containing the JWT token and ID of the account used to authenticate.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 42171f96-43d7-44a5-8a8b-52f713d7ccef

  /register:
    post:
      tags:
        - accounts
      summary: Creates a new account
      description: Creates a new account from the provided name and password from the request body.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        200:
          description: Account json object with obfuscated password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

  /tasks/{accountId}:
    get:
      tags:
        - tasks
      summary: Returns a list of tasks.
      description: Returns a list of tasks associated with the provided `accountId`.
      parameters:
        - name: accountId
          description: The account ID to retrieve tasks for.
          in: path
          schema:
            type: string
            example: 42171f96-43d7-44a5-8a8b-52f713d7ccef
      responses:
        200:
          description: List of Tasks json objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      tags:
        - tasks
      summary: Create a new task or update existing task.
      description: Create a new task or update existing task if the `taskId` value matches an existing task.
      parameters:
        - name: accountId
          description: The account ID to retrieve tasks for.
          in: path
          schema:
            type: string
            example: 42171f96-43d7-44a5-8a8b-52f713d7ccef
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: Task created successfully.

  /tasks/{accountId}/{taskId}:
    delete:
      tags:
        - tasks
      summary: Delete a task
      parameters:
        - name: accountId
          description: The account ID to verify claim.
          in: path
          schema:
            type: string
            example: 42171f96-43d7-44a5-8a8b-52f713d7ccef
        - name: taskId
          description: The task ID to delete
          in: path
          schema:
            type: string
            example: 42171f96-43d7-44a5-8a8b-52f713d7ccef
      responses:
        200:
          description: Task successfully deleted
        400:
          description: Account ID or Task ID was not provided in the url
        401:
          description: The account ID claim in the JWT does not match the account ID.


components:
  schemas:
    Account:
      type: object
      properties:
        name:
          type: string
          example: Bob

        password:
          type: string
          example: Hunter2

        id:
          type: string
          example: 42171f96-43d7-44a5-8a8b-52f713d7ccef
          readOnly: true

      required:
        - name

    Task:
      type: object
      properties:
        title:
          type: string
          description: The title of the task.
          example: Do the dishes
          default: empty string
          required: true
        accountId:
          type: string
          description: The account ID that this task belongs to.
          example: 42171f96-43d7-44a5-8a8b-52f713d7ccef
          default: empty string
          required: true
        created:
          type: integer
          description: The timestamp in milliseconds since EPOCH when this task was created.
          default: 0
          example: 1707607550
        modified:
          type: integer
          description: The timestamp in milliseconds since EPOCH when this task was last modified.
          example: 1707607551
          readOnly: true
        due:
          type: integer
          description: The timestamp in milliseconds since EPOCH when this task is due. A value of -1 indicates no due date.
          default: -1
          example: 1707607551
          required: false
        completed:
          type: boolean
          description: Whether this task has been completed.
          default: false
          example: false
        description:
          type: string
          default: empty string
          description: The optional description of this task
          example: "Optional description string"
        taskId:
          type: string
          default: empty string
          example: 42171f96-43d7-44a5-8a8b-52f713d7ccef
          readOnly: true